# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PPCApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'FontAwesome.swift'

  # Pods for PPCApp

  target 'PPCAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
